### ISSUE TITLE
Error loading llama3 tokenizer

### ISSUE THREAD

**Issue by hexastrayer** [ictnlp/LLaMA-Omni#2]
Incorrect path_or_model_id: '/data/fangqingkai/Omni/models/LLM/Meta-Llama-3-8B-Instruct'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by Poeroz** [comment]
Thank you for pointing out the error. We accidentally included an absolute path in the code, but it's not needed. You can safely delete it, and we've already fixed this issue in the new version.
