### ISSUE TITLE
About gradio_web_server | Models: []

### ISSUE THREAD

**Issue by ZxnSnowy** [ictnlp/LLaMA-Omni#25]
I first run the "python -m omni_speech.serve.model_worker --host myIP --controller http://myIP:10000 --port 40000 --worker http://myIP:40000 --model-path Llama-3.1-8B-Omni --model-name Llama-3.1-8B-Omni --s2s" command.
ERROR:
2024-09-23 18:07:16 | ERROR | stderr |  You may consider adding ignore_mismatched_sizes=True in the model from_pretrained method.
So I changed builder.py:       
 model = model_cls.from_pretrained(
            model_path,
            low_cpu_mem_usage=False,
            ignore_mismatched_sizes=True,
            **kwargs
        )
No mistake reported but run “python -m omni_speech.serve.gradio_web_server --host myIP --controller http://myIP:10000 --port 8000 --model-list-mode reload --vocoder vocoder/g_00500000 --vocoder-cfg vocoder/config.json”.
ERROR:Models: []
![1727145966680](https://github.com/user-attachments/assets/42f983a7-7587-4f16-bb30-c23256d20094)

**Comment by ZxnSnowy** [comment]
The size mismatch ERROR:
![Snipaste_2024-09-24_18-01-42](https://github.com/user-attachments/assets/a0888bc4-a8d6-4250-be38-be297c419638)

![Snipaste_2024-09-24_17-55-54](https://github.com/user-attachments/assets/3faa9490-c187-44c6-b0d3-80025d6caa14)

**Comment by JeckerWen** [comment]
Did you solve this problem?
