### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by UestcJay** [ictnlp/LLaMA-Omni#3]
God Work! I hava some questions, `tgt_units` is discrete speech token generated by e Hidden-unit BERT? Do you think this kind of text hiddenstate directly upsamples to non-autoregressive to get speech token and anygpt this kind of Expanding Vocabulary to integrate speech discrete token.
Which method has more potential for representations into LLM?

**Comment by Poeroz** [comment]
Yes. The speech code we use is the discrete unit generated by HuBERT. Our model architecture and SpeechGPT/AnyGPT follow two different technical approaches. I believe that the latter, which is a native multimodal model, has a higher potential ceiling if sufficient data and training resources are available. However, in resource-constrained environments, our approach can achieve better results at a lower training cost.

**Comment by UestcJay** [comment]
Thank you for your reply, because the length of your hiddenstate should be the same as the text token length. When streaming inference, how to determine the Chunk Size so that the token it truncates is a complete text? Does this need to be considered?

**Comment by Poeroz** [comment]
Thank you for your question. Currently, we are using the simplest fixed chunk size, and the results are still acceptable. If you want to further reduce the occurrence of speech being cut off in the middle of words, one of the simplest possible methods might be to only input the current chunk into the vocoder for synthesis when the corresponding text token represents the end of a word. Perhaps you could give it a try.
