### ISSUE TITLE
请问下hubert具体用的哪个模型

### ISSUE THREAD

**Issue by yuguochencuc** [ictnlp/LLaMA-Omni#6]
hi房庆凯：
想请问下你这里的hubert具体用的哪个模型，以及聚类是否是1000类呀。是否有开源的链接可以提供一下呢。（给你发了邮箱，期待你的回复）

**Comment by step-out** [comment]
Hi Guochen：
请问您知道HuBERT的具体模型了吗，可否分享下呢？期待回复😊
